### ISSUE TITLE
ten_years

### ISSUE THREAD

**Issue by htwang1134** [3box/ceramic-anchor-allowlist#21]
# Team
ten.
# Discord
Snowofo#6566
# Use Case
Offering node as a service for other dapps
# Overview
8vcpu-16gb-50gb
version: "2"
services:
lotus:
container_name: js-ceramic
image:  ceramicnetwork/js-ceramic:testnet-clay
restart: always
volumes:
- ./:/root/.ceramic
- ./logs:/root/.ceramic/logs # Path to daemon logs
- ./statestore:/root/.ceramic/statestore
## Ceramic State Store persistence
Making periodic volume snapshots
## IPFS Repo persistence:
Making periodic volume snapshots

## Static Egress IP:
8.218.156.14

**Comment by baiyibo** [comment]
hi bro, i need your help,  my js-ceramic container start error:
Ceramic daemon failed to start up:
Error: Ceramic mainnet is not yet supported
whar`s that mean , Is it because my IP address is not on the white list？
Like you, I need to submit my own node information here. Have I obtained the permission to connect to the main network？

**Comment by smrz2001** [comment]
Is this for running your node on Clay?

**Comment by htwang1134** [comment]
> 

yes

**Comment by htwang1134** [comment]
> 各位好兄弟，我需要你的帮助，我的js-ceramic container start error: Ceramic daemon failed to start: Error: Ceramic mainnet is not yet supported is ，是不是因为我的IP地址不在白字上？ 和你一样，我需要提交自己的节点信息。我在这里是否获得了连接主网的权限？

这个需要申请白名单才能连接主网
